content_css: /assets/application.css?body=1
theme_advanced_resizing: true
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
theme_advanced_buttons1 : "bold,italic,underline,forecolor,separator,justifyleft,justifycenter,justifyright,separator,formatselect,separator,bullist,numlist,separator,outdent,indent,separator,link,unlink,separator,image,separator,code"
theme_advanced_buttons2 : "charmap,separator,table,separator,row_before,row_after,delete_row,separator,col_before,col_after,delete_col"
theme_advanced_buttons3 : ""
theme_advanced_blockformats : "p,h2,h3,h4,h5,h6,blockquote,pre"
plugins:
  - table
